apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: k8straining
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  master.conf: | 
    bind 0.0.0.0
    protected-mode yes
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    requirepass "P@ssw0rd"
  slave.conf: |
    slaveof redis-0.azure-vote-back 6379
    masterauth "P@ssw0rd"
