apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: vote-wget
  namespace: k8straining
  labels:
    addonmanager.kubernetes.io/mode: Reconcile  
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wget
            image: busybox
            args:
            - /bin/sh
            - -c
            - wget -q -O - http://vote-host.xip.io
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 20m
                memory: 64Mi            
          restartPolicy: OnFailure
