apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vote
  namespace: k8straining
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 23.98.121.24.xip.io 
    http:
      paths:
      - backend:
          serviceName: azure-vote-front
          servicePort: 80
        path: /
