apiVersion: batch/v1
kind: Job
metadata:
  name: vote-wget
  namespace: k8straining
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  template:
    spec:
      containers:
      - name: wget
        image: busybox
        command: ["/bin/sh", "-c", "wget -q -O - http://vote-host.xip.io"]
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 20m
            memory: 64Mi        
      restartPolicy: Never
  backoffLimit: 4
