apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limitrange
  namespace: k8straining
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      memory: 64Mi
    max:
      memory: 256Mi
    min:
      memory: 64Mi
    type: Container