apiVersion: v1
kind: LimitRange
metadata:
  name: memory
  namespace: k8straining
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      memory: 16Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu
  namespace: k8straining
  labels:
    addonmanager.kubernetes.io/mode: Reconcile  
spec:
  limits:
  - default:
      cpu: 200m
    defaultRequest:
      cpu: 10m
    type: Container