apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limitrange
  namespace: k8straining
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      memory: 16Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limitrange
  namespace: k8straining
spec:
  limits:
  - default:
      cpu: 200m
    defaultRequest:
      cpu: 50m
    type: Container