apiVersion: v1
kind: ResourceQuota
metadata:
  name: k8straining
  namespace: k8straining
  labels:
    addonmanager.kubernetes.io/mode: Reconcile  
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
