apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: k8straining
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
type: Opaque
data:
  # base64 encode of P@ssw0rd
  password: UEBzc3cwcmQ=
