apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  namespace: k8straining
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: azure-vote-front
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front-nodeport
  namespace: k8straining
spec:
  type: NodePort
  ports:
  - nodePort: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: azure-vote-front
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  clusterIP: None
  selector:
    app: redis